FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    make \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Kopiujemy kod źródłowy hiredis do kontenera
COPY . .

# Kompilujemy bibliotekę
RUN make
